out: bin/configgen.exe
main: ConfiggenExe
debug: Yes
depends:
 - bin/FullSerializer.dll
 - bin/UnityEngine.dll
defines: UNITY_EDITOR
files:
 - Configuration/Config.cs
 - Configuration/LaunchConfig.cs
 - Configuration/Editor/Utility/InstanceUtility.cs
 - Configuration/Editor/Utility/TypeUtilityEditorOnly.cs
 - Configuration/Utility/TypeUtility.cs
 - Configuration/Utility/ClassFieldFilter.cs
 - Configuration/Utility/NamespaceUtility.cs
 - Configuration/Editor/Main/ConfiggenExe.cs
 - Configuration/Editor/Main/MyCustomEnumConverter.cs
 - Configuration/Editor/Main/MyDictionaryConverter.cs
folders:
 - Scripts/Utility/*.cs
 - Scripts/LogUtil/*.cs
 - Configuration/Attribute/*.cs
 - Configuration/AutoGen/*.cs
 - Configuration/Editor/BinGenerator/*.cs
 - Configuration/LaunchConfig/*.cs
 - Configuration/POD/*.cs